joint1_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: joint1
    joint_speed: 1
    motor:
        id: 15
        init: 2047
        min: 0
        max: 9999
        #min: 1536
        #max: 3070

