TrajectoryPlannerROS:
  max_vel_x: 0.2
  min_vel_x: 0.05
  max_vel_theta: 0.7
  min_vel_theta: -0.5
  min_in_place_vel_theta: 0.1

  holonomic_robot: false

  yaw_goal_tolerance: 0.05
  xy_goal_tolerance: 0.05

  meter_scoring: true
  pdist_scale: 10
