# Global parameters
static_map: false
resolution: 0.05

# Obstacles layer
observation_sources: kinect
kinect:
    topic: /camera/depth/points
    sensor_frame: camera_depth_optical_frame
    data_type: PointCloud2
    clearing: true
    marking: true
    max_obstacle_height: 0.5
    obstacle_range: 1.0
    raytrace_range: 1.5

# Inflation layer
inflation_radius: 0.25

footprint: [[0, -0.25], [0.1, -0.2], [0.1, 0.2], [0, 0.25], [-0.3, 0.2], [-0.3, -0.2]]
