global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 2.0
  publish_frequency: 1.0
  width: 8.0
  height: 8.0
  origin_x: -4.0
  origin_y: -4.0

  observation_sources: laser
  laser:
    topic: /scan
    data_type: LaserScan
    clearing: true
    marking: true
    obstacle_range: 2.0
